# httpproxy.yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: myapp
spec:
  virtualhost:
    fqdn: foo-myapp.bar.com
  routes:
    - conditions:
      - prefix: /
      services:
        - name: s1
          port: 80